### PR TITLE
Use collections.abc for some imports if running under Python 3

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by jveitchmichaelis** [comment]
Could you update this to use `six.moves.collections_abc`? This should avoid the linting errors.

**Comment by mulkieran** [comment]
> Could you update this to use `six.moves.collections_abc`, please? I think should avoid the linting errors. Looks like the linter doesn't care if it's a conditional import and just fails.
> 
> It was added fairly recently ([benjaminp/six#241](https://github.com/benjaminp/six/pull/241))

I think it was actually not added.

**Comment by jveitchmichaelis** [comment]
Hmm, the docs list it under supported renames: https://six.readthedocs.io/ and the commit is here: https://github.com/benjaminp/six/commit/0dc54ead62c7fb06edabf1ff22fb71c0c6d958e1

**Comment by mulkieran** [comment]
> The commit is here: [benjaminp/six@0dc54ea](https://github.com/benjaminp/six/commit/0dc54ead62c7fb06edabf1ff22fb71c0c6d958e1) and it's in the stable docs.
> 
> If it's not live yet (not sure why though, it should be in 1.13.0), a workaround could be to manually add it:
> 
> ```
> m = six.MovedModule("collections_abc", "collections", "collections.abc" if sys.version_info >= (3, 3) else "collections")
> six.add_move(m)
> ```

Yes, I see it came out in this year's release about a month ago after a deal of conflict. Let me see what I can do.

**Comment by mulkieran** [comment]
Whoops! typo...should be fixed now.

**Comment by mulkieran** [comment]
New error with Hypothesis running 3.6.61

**Comment by mulkieran** [comment]
New error with hypothesis running 3.66.1.

**Comment by mulkieran** [comment]
rebased.

**Pull request merged**
