### PR TITLE
Parameterize MonitorObserver on its PyQt* import.

### PR DESCRIPTION
**Pull request by mulkieran**
Note that importing pyqt4 and pyqt5 will raise a RuntimeError.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@tobiasgehring, I'm considering this as a partial alternative. I hadn't looked closely enough at your PR to realize that the code of the two was identical...only the imports were different. This puts all the code in one place, but is fancier.

However, I'm not sure it is a complete solution. The problem is that you can not import both PyQt4.QtCore and PyQt5.QtCore at once w/out raising a runtime error. I think that it might be better to have one pyqt module. Importing that module would result either in an import of PyQt4 or PyQt5 depending on some flag that could be set when pyudev is loaded. I believe that this is similar to matplotlib's approach.

Is there anything that you can tell me about your use case to help clarify what would make sense?

**Comment by tobiasgehring** [comment]
I have never used Qt4 but assuming that there will be Qt6 at some point,
it is probably a good idea to unify as much as possible. The same might
actually be true for gtk2/gtk3, but I don't remember exactly right now
what I had to change in order to make the gtk2 code work for gtk3.
I don't know how flags on module import work and how easy it is to
choose an implementation. I'm pretty sure that nobody will ever use
different gui toolkits within a single application :) Be aware that
there is also pySide, a replacement for pyqt4 and it is currently
supported by pyudev. According to their website they are working on a
Qt5 implementation. Apparently the difference between pySide and pyqt4
in our code (apart from other imports) is that signals are generated
slightly differently (Signal(...) vs. pyqtSignal()), but that's it.

My personal use case is that I use pyudev to get notified about usb
device change events in my qt5 applications (only under linux of course,
for Windows I use something else). Notification means that an event
within the qt5 event loop is generated once a usb device is plugged in
our out. I will use only qt5 in the future (maybe until a newer version
arrives). The reason I once wrote the wx monitor is that I have used wx
widgets in some older applications. A while ago I compared wx, gtk3 and
qt5 for my purposes and during that I was also looking into how to get
usb device change notifications within the different gui frameworks.
That's the reason I modified also the gtk2 monitor code to support gtk3
(gobject introspection). I will not use it in the future but I thought
that somebody might find it useful.

**Comment by tobiasgehring** [comment]
in a gtk3 application I use matplotlib to make plots. There I explicitly
import a gtk3 backend:

from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo
as FigureCanvas

**Comment by mulkieran** [comment]
My ultimate plan is to move all this pyqt handling into a separate package. But this is about all the changes I think are worth while now. @tobiasgehring , could you test it in any way that makes sense for you?

**Comment by tobiasgehring** [comment]
I can test it with pyqt5 in my existing programs, sure.

**Comment by mulkieran** [comment]
ok, thanks.

**Comment by mulkieran** [comment]
@tobiasgehring If you're happy with this, I'll go ahead and push it.

**Comment by tobiasgehring** [comment]
I'll test it Friday with a real device.

**Comment by mulkieran** [comment]
ok, thanks again.

**Comment by tobiasgehring** [comment]
works very nice and smoothly :)

**Pull request merged**
