### PR TITLE
support for gobject introspection (gtk3)

### PR DESCRIPTION
**Pull request by tobiasgehring**
new pull request based on current development branch

### CODE REVIEW

**Comment by mulkieran** [comment]
@tobiasgehring , I don't think that you feel that this is urgent, so I'm going to hold off on this, as my current plan is to split these little GUI bits into separate packages. That way their dependencies can be handled more correctly.

**Comment by tobiasgehring** [comment]
yeah, the gobject introspection support is not exactly important for me
right now as I don't use gtk3 at the moment.

**Comment by mulkieran** [comment]
This should be reopenable?

**Comment by tobiasgehring** [comment]
I think so. The best would be to have a similar implementation as you made for qt. gtk2/gtk3 are pretty much the same but for imports and names (so a bit less the same as qt4 and qt5).

**Pull request closed without merging**
