### PR TITLE
Get rid of six dependency

### PR DESCRIPTION
**Pull request by z3ntu**
Obviously this makes pyudev incompatible with Python 2 but Python 2 will
be dead soon anyways.

https://pythonclock.org/

### CODE REVIEW

**Comment by z3ntu** [comment]
I somehow can't get Travis to run on this commit/PR...

**Comment by mulkieran** [comment]
@z3ntu It's because of https://travis-ci.community/t/draft-pull-requests-not-being-built/2434.

**Comment by mulkieran** [comment]
@z3ntu Thanks, but I doubt this change would go over well with some users. Feel free to leave it open, maybe in 2025 it'll be safe to do it.

**Comment by z3ntu** [comment]
Now Travis is running.

I'm also dropping the link https://python3statement.org/ here; I think Python 2 can be dropped before that, as Python 2 users can still use old release of pyudev.

Anyways, it's your decision, I just dropped this PR here :)

**Comment by mulkieran** [comment]
Ok, thanks! Looks like I need to do a pass to fix up some of the CI first, though.

**Comment by mulkieran** [comment]
Restarted Travis...

**Comment by mulkieran** [comment]
Looks like the remaining Travis errors are actually occasioned by this PR. So, they would require further investigation as well.

**Comment by z3ntu** [comment]
Tests now succeed for all 3.x versions and fail for 2.x (so 2.7 and pypy)

**Comment by mulkieran** [comment]
Ok, thanks!

**Comment by z3ntu** [comment]
Just looking through my old forks, is this still wanted in pyudev? I see py2 support has been dropped more than a year ago but six is still required.

**Comment by mulkieran** [comment]
Thank you for checking. I hope to cut a new release that officially drops py2 support in maybe a week. If you have time could you close this PR and make a new one against master branch?

**Comment by z3ntu** [comment]
CI is green for me now: https://github.com/z3ntu/pyudev/actions/runs/1714699866

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
@z3ntu Plz rebase one last time and I'll be able to merge immediately. Thx!

**Comment by z3ntu** [comment]
Also remove six dependency from CI now.

CI is green again: https://github.com/z3ntu/pyudev/actions/runs/1799264471

**Comment by mulkieran** [comment]
thx!

**Pull request merged**
