### PR TITLE
added support for pyqt5 monitor observer

### PR DESCRIPTION
**Pull request by tobiasgehring**
new pull request for a pyqt5 monitor observer against latest development branch

### CODE REVIEW

**Comment by mulkieran** [comment]
Please revise the PR with requested changes and I'll be happy to merge into develop branch.

**Comment by tobiasgehring** [comment]
done

**Comment by mulkieran** [comment]
Please merge the two commits into a single commit and fix the minor typo "turing" as well.

**Comment by tobiasgehring** [comment]
done

**Pull request merged**
