### PR TITLE
Drop support for Python 2

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/pyudev/pyudev/issues/380.

---

Should EOL Python 3.1-3.4 also be dropped?

Version | Release date | Supported until
--- | ---------- | ----------
2.6 | 2008-10-01 | 2013-10-29
2.7 | 2010-07-03 | 2020-01-01
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29
3.4 | 2014-03-16 | 2019-03-16

Source: https://en.wikipedia.org/wiki/CPython#Version_history

### CODE REVIEW

**Comment by mulkieran** [comment]
Thanks for the contributions. Dropping support for Python2 can not happen in the next release. It is possible that it can happen in the one after that. This will take a few months, and I should expect it to go into the next year. As we, I hope, approach that point, I'll have to ask you to split out your changes into separate PRs, so that they can be considered separately, as much as possible.

**Comment by hugovk** [comment]
Sure, just ping me when it's time!

**Comment by mulkieran** [comment]
Ok, thanks!

**Comment by hugovk** [comment]
This has conflicts, closing until it's time.

**Comment by mulkieran** [comment]
Thanks for the help! I am still planning to do this, but have too limited time right now.

**Pull request closed without merging**
