### PR TITLE
python: fix deprecated collections imports

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@archlinux.org>

### CODE REVIEW

**Comment by mulkieran** [comment]
Thanks, but you'll have to use six: https://github.com/benjaminp/six/issues/155. It would be nice for me to be able to drop the Python2 dependency, but that wouldn't go over well w/ users of the library.

**Comment by FFY00** [comment]
Python 2 is EOL in 3 months. Why not create a release now and then apply the patch? People that really need Python 2 will still have the a recent release.

**Comment by mulkieran** [comment]
@FFY00 Dropping support for Python 2 is a _much_ bigger decision than just using six for the incompatibility here. Why not open an issue for dropping Python2, and see what the reactions are?

It would take a bit of work to create a new release. OTOH, a new release would probably be a good thing, as there's quite a bit of cruft that needs addressing.

**Comment by FFY00** [comment]
Sure, I agree. I will create an issue.

**Comment by mulkieran** [comment]
Closed in favor of #386.

**Pull request closed without merging**
