### PR TITLE
Switch to new style gi.repository.GLib imports

### LINKED ISSUE #41: Support for Gtk 3
Add support for Gtk 3 based on gobject 3.

### PR DESCRIPTION
**Pull request by Skrupellos**
Should fix #41 (Gtk 3 style imports).

### CODE REVIEW

**Comment by mulkieran** [comment]
Thanks @Skrupellos. I don't ever use this part of the pyudev functionality, so I'm not in a position to actually review it for correctness. Can you give a little more explanation of what this solves and how?

**Comment by Skrupellos** [comment]
As described in https://bugzilla.gnome.org/show_bug.cgi?id=709183, you need to import modules as `gi.repository.GLib` and `gi.repository.GObject`. The modules `glib` and `gobject` don't exist any more. If you import `gi`, you get dummy modules raising an exception if used:
```python
>>> import glib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'glib'
>>> import gi
>>> import glib
>>> glib.MainLoop()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/pyudev/.direnv/python-3.7.7/lib/python3.7/site-packages/gi/__init__.py", line 72, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

**Comment by mulkieran** [comment]
> As described in https://bugzilla.gnome.org/show_bug.cgi?id=709183, you need to import modules as `gi.repository.GLib` and `gi.repository.GObject`. The modules `glib` and `gobject` don't exist any more. If you import `gi`, you get dummy modules raising an exception if used:
> 
> ```python
> >>> import glib
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'glib'
> >>> import gi
> >>> import glib
> >>> glib.MainLoop()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/tmp/pyudev/.direnv/python-3.7.7/lib/python3.7/site-packages/gi/__init__.py", line 72, in __getattr__
>     raise AttributeError(_static_binding_error)
> AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
> ```

Wow! That's my bug report you're referencing (under a different name and years before I became involved with pyudev).

**Comment by mulkieran** [comment]
@Skrupellos I'll merge this tomorrow as-is, unless you have any objections. Let me know, thx.

**Pull request merged**
