### PR TITLE
added support for gobject introspection (gi)

### PR DESCRIPTION
**Pull request by tobiasgehring**
Hi,
I took the version from Adrián Pardini (inaes-tic/pyudev) and fixed the open issues. Tests run through smoothly.
Cheers,
Tobias

### CODE REVIEW

**Comment by mulkieran** [comment]
Hi!

I'm engaged in resuscitating this project, I hope.

Could you give me a little more information on your two pull requests?

Also, could you update from develop branch and repush them both and see what Travis CI says about them?

Thanks,

**Comment by tobiasgehring** [comment]
Hi,

I'm travelling these days. Are you fine or do you still need me to do
something?

Cheers,

Tobias

**Comment by mulkieran** [comment]
I'll still need to understand what you're doing and why.

Take your time, though, I put out a resuscitation release
that just includes bug fixes, so these PR's wouldn't make
it until next release anyway.

Also, we are experiencing technical difficulties w/ Travis CI.

Thanks,

- mulhern

----- Original Message -----

**Comment by tobiasgehring** [comment]
Hi mulhern,

For qt5 it is quite simple. I basically copied the code for qt4 and replaced 4
with 5. Could be that there are api changes between the qt version, don't
remember.

I actually don't know what travis ci is...

Cheers, Tobias

On Tue, Sep 08, 2015 at 10:06 AM, mulkieran < notifications@github.com [notifications@github.com] > wrote:
I'll still need to understand what you're doing and why.

Take your time, though, I put out a resuscitation release
that just includes bug fixes, so these PR's wouldn't make
it until next release anyway.

Also, we are experiencing technical difficulties w/ Travis CI.

Thanks,

- mulhern

----- Original Message -----
> From: "Tobias Gehring" <notifications@github.com>
> To: "pyudev/pyudev" <pyudev@noreply.github.com>
> Cc: "mulkieran" <amulhern@redhat.com>
> Sent: Tuesday, September 8, 2015 9:46:26 AM
> Subject: Re: [pyudev] added support for gobject introspection (gi) (#77)
>
> Hi,
>
> I'm travelling these days. Are you fine or do you still need me to do
> something?
>
> Cheers,
>
> Tobias
>
> On 08/24/2015 03:06 PM, mulkieran wrote:
> > Hi!
> >
> > I'm engaged in resuscitating this project, I hope.
> >
> > Could you give me a little more information on your two pull requests?
> >
> > Also, could you update from develop branch and repush them both and see
> > what Travis CI says about them?
> >
> > Thanks,
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pyudev/pyudev/pull/77#issuecomment-134342896>.
> >
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/pyudev/pyudev/pull/77#issuecomment-138564262
—
Reply to this email directly or view it on GitHub
[https://github.com/pyudev/pyudev/pull/77#issuecomment-138569998] .[https://github.com/notifications/beacon/ABV7UjOqc-J3z9vkZlK6VeJEKLOpETrnks5ovuLwgaJpZM4Dnhbi.gif]

**Comment by mulkieran** [comment]
It's the continuous integration framework that didn't run its tests back when you first submitted the PR, because the then maintainer wasn't keeping up the account. Since then, I've gotten all CI tests passing, and I'm aiming to keep it that way.

The closing was an artifact of my deleting develop branch, and starting a new one.

**Comment by tobiasgehring** [comment]
did you fix the technical difficulties w/ Travis CI so that I can work
on a new patch?

**Comment by mulkieran** [comment]
If the tests don't get started by a pull request then something is wrong. If they don't pass...then something may be wrong.

**Comment by mulkieran** [comment]
Obsoleted by #114.

**Pull request closed without merging**
