### PR TITLE
Fix eudev

### PR DESCRIPTION
**Pull request by sulincix**
find_library function sometimes not find eudev. I replace with try catch logic. Now working good.

### CODE REVIEW

**Comment by mulkieran** [comment]
thanks for your contribution. Unfortunately, I think that the proposaed change would make it likely that the library would stop working for others. You might want to try debugging pyudev to try to discover why find_library is not finding the version of libudev that is on your system.

**Comment by sulincix** [comment]
eudev is different than libudev but has same symbol table. Also try except way better than using find_library function. (If libudev exists but not working, current way cannot catch error and print python error or segmentation fault error.)

**Comment by sulincix** [comment]
image

**Comment by mulkieran** [comment]
@sulincix What I'm hoping is that you can figure out why https://github.com/python/cpython/blob/master/Lib/ctypes/util.py#L206 is not returning your file. I'm guessing that the line ```return _get_soname(_findLib_gcc(name))``` is returning ```None```, but beyond that I'm unable to go.

**Comment by sulincix** [comment]
Hmmm. This source uses very bad way to find library. This is required gcc. I think most of end user distributions does not have gcc command as preinstalled. (or may uses clang) We must replace bad function with better one.

**Comment by mulkieran** [comment]
> Hmmm. This source uses very bad way to find library. This is required gcc (and binutils). I think most of end user distributions does not have gcc command as preinstalled. (or may uses clang) We must replace bad function with better one.

I understand what you're saying regarding gcc and clang. Are there any ongoing Python PRs or issues about this problem? If there are, and they look viable, then it might be possible to port their changes into pyudev. But I can't remove the existing ```find_libary``` call, because I feel sure other users of pyudev are getting the behavior that they need and would lose that behavior if I removed it.

**Comment by sulincix** [comment]
Okay. We can try find_library function. If it return none we must try CDLL for fallback.

**Pull request closed without merging**
