### PR TITLE
Do not install the tests as a module.

### PR DESCRIPTION
**Pull request by dashea**

### CODE REVIEW

**Comment by mulkieran** [comment]
Please add a bit more of a justification to commit message.

**Comment by mulkieran** [comment]
Well, I looked at the commits associated with ```tests/__init__.py``` and I see the problem.

Do you expect this will fix all the problems described in commit 08863e220ed8df6e7a55fb91558b75abf0940dd9?

**Comment by dashea** [comment]
I have no idea what it will do to tox, but I was aiming to not install pyudev/tests as <pythonlib>/site-packages/tests.

**Comment by mulkieran** [comment]
I have a feeling this is why the best prepared people put all the packages they want to install in a ```src``` subdirectory.

**Comment by mulkieran** [comment]
PR #94 should fix the problem in a more principled and testable way.

**Pull request closed without merging**
